// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/domain/interfaces/repository.go

// Package interfaces is a generated GoMock package.
package interfaces

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIMemoryLinkRepository is a mock of IMemoryLinkRepository interface.
type MockIMemoryLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIMemoryLinkRepositoryMockRecorder
}

// MockIMemoryLinkRepositoryMockRecorder is the mock recorder for MockIMemoryLinkRepository.
type MockIMemoryLinkRepositoryMockRecorder struct {
	mock *MockIMemoryLinkRepository
}

// NewMockIMemoryLinkRepository creates a new mock instance.
func NewMockIMemoryLinkRepository(ctrl *gomock.Controller) *MockIMemoryLinkRepository {
	mock := &MockIMemoryLinkRepository{ctrl: ctrl}
	mock.recorder = &MockIMemoryLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMemoryLinkRepository) EXPECT() *MockIMemoryLinkRepositoryMockRecorder {
	return m.recorder
}

// IsFirstVisit mocks base method.
func (m *MockIMemoryLinkRepository) IsFirstVisit(url string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFirstVisit", url)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFirstVisit indicates an expected call of IsFirstVisit.
func (mr *MockIMemoryLinkRepositoryMockRecorder) IsFirstVisit(url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFirstVisit", reflect.TypeOf((*MockIMemoryLinkRepository)(nil).IsFirstVisit), url)
}
